/**
 * Apple .strings and .stringsdict format support
 * Supports parsing and exporting .strings files
 */

export interface StringsTranslation {
  key: string;
  value: string;
  comment?: string;
}

/**
 * Parse a .strings file (UTF-16 or UTF-8)
 */
export function parseStrings(content: string): Array<{
  key: string;
  value: string;
  description?: string;
}> {
  const translations: Array<{
    key: string;
    value: string;
    description?: string;
  }> = [];

  // .strings files use a simple key-value format:
  // "key" = "value";
  // /* comment */
  // "key" = "value";

  const lines = content.split("\n");
  let currentComment: string | undefined;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    // Extract comment
    const commentMatch = line.match(/\/\*(.*?)\*\//);
    if (commentMatch) {
      currentComment = commentMatch[1].trim();
    }

    // Extract key-value pair
    const match = line.match(/"([^"]+)"\s*=\s*"([^"]*)";/);
    if (match) {
      const [, key, value] = match;
      translations.push({
        key: key.replace(/\\"/g, '"').replace(/\\n/g, "\n"),
        value: value.replace(/\\"/g, '"').replace(/\\n/g, "\n"),
        description: currentComment || undefined,
      });
      currentComment = undefined;
    }
  }

  return translations;
}

/**
 * Export translations to .strings format
 */
export function exportToStrings(
  translations: Array<{
    key: string;
    source: string;
    target?: string;
    description?: string;
  }>
): string {
  let output = "/*\n";
  output += "  Localizable.strings\n";
  output += "  Generated by LinguaFlow\n";
  output += "*/\n\n";

  for (const t of translations) {
    if (t.description) {
      output += `/* ${t.description} */\n`;
    }

    const key = t.key.replace(/"/g, '\\"').replace(/\n/g, "\\n");
    const value = (t.target || t.source).replace(/"/g, '\\"').replace(/\n/g, "\\n");

    output += `"${key}" = "${value}";\n\n`;
  }

  return output;
}

/**
 * Parse a .stringsdict file (plist XML format)
 * This is a simplified parser - full .stringsdict support requires plist parsing
 */
export function parseStringsDict(content: string): Array<{
  key: string;
  value: string;
  description?: string;
}> {
  // .stringsdict files are XML plist files
  // For now, we'll extract basic key-value pairs
  // Full implementation would require plist parsing library

  const translations: Array<{
    key: string;
    value: string;
    description?: string;
  }> = [];

  // Extract keys and values from XML
  const keyMatches = content.matchAll(/<key>([^<]+)<\/key>/g);
  const stringMatches = content.matchAll(/<string>([^<]+)<\/string>/g);

  const keys = Array.from(keyMatches).map((m) => m[1]);
  const values = Array.from(stringMatches).map((m) => m[1]);

  for (let i = 0; i < Math.min(keys.length, values.length); i++) {
    translations.push({
      key: keys[i],
      value: values[i],
    });
  }

  return translations;
}

